on:
  push:
    branches:
      - new-site

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn
      - name: Setup Yarn
        uses: mskelton/setup-yarn@latest
      - name: Install NPM Dependencies
        run: yarn install --frozen-lockfile
      - name: Generate Static Export with Next.js
        run: yarn export
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: acikkaynak-website
          directory: out
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
